language: python

python:
  - 2.7

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - pip install -r requirements.txt
  - pip install .

script:
  - cd tests/
  - nosetests --with-coverage --cover-package=dd

after_success:
  - coveralls

