language: python

matrix:
  include:
    - python: 2.7
      env: PYDOT="http://pydot.googlecode.com/files/pydot-1.0.28.tar.gz"
    - python: 3.5
      env: PYDOT=pydot3k

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install $PYDOT
  - python setup.py install --fetch --cudd

script:
  - cd tests/
  - nosetests --with-coverage --cover-package=dd

after_success:
  - coveralls

